name: upload_artifact
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Step1 - Checkout code
        uses: actions/checkout@v3
      - name: Step2 - Install dependencies
        run: npm ci
      - name: Step3 - Lint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Step1 - Checkout code
        uses: actions/checkout@v3
      - name: Step2 - Install dependencies
        run: npm ci
      - name: Step3 - Lint
        run: npm run lint
      - name: Step4 - Run tests
        run: npm test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Step1 - Checkout code
        uses: actions/checkout@v3
      - name: Step2 - Install dependencies
        run: npm ci
      - name: Step3 - Build project
        run: npm run build
      - name: Step4 - Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-package
          path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Step1 - Checkout code
        uses: actions/checkout@v3
      - name: Step2 - Install dependencies
        run: npm ci
      - name: Step3 - Deploy project
        run: echo "Deploying application..."